/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "星夜引擎",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.png",
        "type": "image/png",
        "sizes": "16x16"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/favicon.png",
        "heroText": "星夜引擎",
        "tagline": "致力于简单/易用/高效的Web跨平台GalGame引擎",
        "actionText": "立刻上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "?",
            "details": "?"
          },
          {
            "title": "?",
            "details": "?"
          },
          {
            "title": "?",
            "details": "?"
          }
        ],
        "footer": "AGPL-3.0 Licensed | Copyleft 2021-2022 灵弦"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0c1a5bd9",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "在线体验",
          "slug": "在线体验"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/extend/",
      "relativePath": "extend/README.md",
      "key": "v-7fd2ee88",
      "path": "/extend/"
    },
    {
      "title": "编写一个简单的命令脚本",
      "frontmatter": {},
      "regularPath": "/extend/command.html",
      "relativePath": "extend/command.md",
      "key": "v-7716948f",
      "path": "/extend/command.html",
      "headers": [
        {
          "level": 2,
          "title": "编写一个简单的命令脚本",
          "slug": "编写一个简单的命令脚本"
        },
        {
          "level": 2,
          "title": "在剧本中使用命令",
          "slug": "在剧本中使用命令"
        },
        {
          "level": 2,
          "title": "Game作用域,初始化舞台对象",
          "slug": "game作用域-初始化舞台对象"
        },
        {
          "level": 2,
          "title": "挂载变量到存档",
          "slug": "挂载变量到存档"
        },
        {
          "level": 2,
          "title": "生命周期函数与减少网络请求",
          "slug": "生命周期函数与减少网络请求"
        },
        {
          "level": 3,
          "title": "初始化",
          "slug": "初始化"
        },
        {
          "level": 3,
          "title": "快进",
          "slug": "快进"
        },
        {
          "level": 3,
          "title": "初次点击",
          "slug": "初次点击"
        }
      ]
    },
    {
      "title": "基本概念",
      "frontmatter": {},
      "regularPath": "/extend/ui.html",
      "relativePath": "extend/ui.md",
      "key": "v-399cd322",
      "path": "/extend/ui.html",
      "headers": [
        {
          "level": 2,
          "title": "基本概念",
          "slug": "基本概念"
        },
        {
          "level": 3,
          "title": "元素",
          "slug": "元素"
        },
        {
          "level": 3,
          "title": "标签",
          "slug": "标签"
        },
        {
          "level": 3,
          "title": "生成器",
          "slug": "生成器"
        },
        {
          "level": 2,
          "title": "标签",
          "slug": "标签-2"
        },
        {
          "level": 3,
          "title": "点击事件标签",
          "slug": "点击事件标签"
        },
        {
          "level": 3,
          "title": "浮动事件标签",
          "slug": "浮动事件标签"
        },
        {
          "level": 3,
          "title": "页面跳转标签",
          "slug": "页面跳转标签"
        },
        {
          "level": 3,
          "title": "变量绑定标签",
          "slug": "变量绑定标签"
        },
        {
          "level": 3,
          "title": "css标签",
          "slug": "css标签"
        },
        {
          "level": 3,
          "title": "js标签",
          "slug": "js标签"
        },
        {
          "level": 2,
          "title": "生成器",
          "slug": "生成器-2"
        },
        {
          "level": 3,
          "title": "克隆生成器",
          "slug": "克隆生成器"
        },
        {
          "level": 3,
          "title": "互斥生成器",
          "slug": "互斥生成器"
        },
        {
          "level": 3,
          "title": "标签生成器",
          "slug": "标签生成器"
        },
        {
          "level": 3,
          "title": "滑块生成器",
          "slug": "滑块生成器"
        },
        {
          "level": 3,
          "title": "单选按钮生成器",
          "slug": "单选按钮生成器"
        },
        {
          "level": 3,
          "title": "多选按钮生成器",
          "slug": "多选按钮生成器"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-455631ec",
      "path": "/guide/"
    },
    {
      "title": "配置python环境",
      "frontmatter": {},
      "regularPath": "/guide/assetzip.html",
      "relativePath": "guide/assetzip.md",
      "key": "v-fc9f918e",
      "path": "/guide/assetzip.html",
      "headers": [
        {
          "level": 2,
          "title": "配置python环境",
          "slug": "配置python环境"
        },
        {
          "level": 2,
          "title": "压缩剧本",
          "slug": "压缩剧本"
        },
        {
          "level": 2,
          "title": "压缩资源",
          "slug": "压缩资源"
        },
        {
          "level": 3,
          "title": "压缩图片资源",
          "slug": "压缩图片资源"
        },
        {
          "level": 3,
          "title": "压缩音频资源",
          "slug": "压缩音频资源"
        },
        {
          "level": 2,
          "title": "使用CDN加速",
          "slug": "使用cdn加速"
        }
      ]
    },
    {
      "title": "配置画布大小",
      "frontmatter": {},
      "regularPath": "/guide/config.html",
      "relativePath": "guide/config.md",
      "key": "v-0b94e857",
      "path": "/guide/config.html",
      "headers": [
        {
          "level": 2,
          "title": "配置画布大小",
          "slug": "配置画布大小"
        },
        {
          "level": 2,
          "title": "配置CG",
          "slug": "配置cg"
        },
        {
          "level": 2,
          "title": "添加音轨",
          "slug": "添加音轨"
        },
        {
          "level": 2,
          "title": "配置全局字体",
          "slug": "配置全局字体"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/preface.html",
      "relativePath": "guide/preface.md",
      "key": "v-079b6e96",
      "path": "/guide/preface.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用条款",
          "slug": "使用条款"
        },
        {
          "level": 2,
          "title": "文档与反馈",
          "slug": "文档与反馈"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/problem.html",
      "relativePath": "guide/problem.md",
      "key": "v-5187b2d5",
      "path": "/guide/problem.html"
    },
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/guide/script.html",
      "relativePath": "guide/script.md",
      "key": "v-576b5a85",
      "path": "/guide/script.html",
      "headers": [
        {
          "level": 2,
          "title": "快速开始",
          "slug": "快速开始"
        },
        {
          "level": 2,
          "title": "需要了解的概念",
          "slug": "需要了解的概念"
        },
        {
          "level": 2,
          "title": "剧本基本格式",
          "slug": "剧本基本格式"
        },
        {
          "level": 2,
          "title": "命令参数",
          "slug": "命令参数"
        },
        {
          "level": 3,
          "title": "文本",
          "slug": "文本"
        },
        {
          "level": 3,
          "title": "名称",
          "slug": "名称"
        },
        {
          "level": 3,
          "title": "目标",
          "slug": "目标"
        },
        {
          "level": 3,
          "title": "文件",
          "slug": "文件"
        },
        {
          "level": 3,
          "title": "坐标",
          "slug": "坐标"
        },
        {
          "level": 3,
          "title": "时间",
          "slug": "时间"
        },
        {
          "level": 3,
          "title": "缓动",
          "slug": "缓动"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令-2"
        },
        {
          "level": 3,
          "title": "对话和语音",
          "slug": "对话和语音"
        },
        {
          "level": 3,
          "title": "更改背景",
          "slug": "更改背景"
        },
        {
          "level": 3,
          "title": "放置立绘",
          "slug": "放置立绘"
        },
        {
          "level": 3,
          "title": "关闭立绘",
          "slug": "关闭立绘"
        },
        {
          "level": 3,
          "title": "移动图片元素",
          "slug": "移动图片元素"
        },
        {
          "level": 3,
          "title": "抖动图片元素",
          "slug": "抖动图片元素"
        },
        {
          "level": 3,
          "title": "播放背景音乐",
          "slug": "播放背景音乐"
        },
        {
          "level": 3,
          "title": "播放环境音",
          "slug": "播放环境音"
        },
        {
          "level": 3,
          "title": "播放视频",
          "slug": "播放视频"
        },
        {
          "level": 3,
          "title": "跳转选项与跳转标识",
          "slug": "跳转选项与跳转标识"
        },
        {
          "level": 3,
          "title": "等待",
          "slug": "等待"
        },
        {
          "level": 2,
          "title": "拆分剧本",
          "slug": "拆分剧本"
        },
        {
          "level": 2,
          "title": "使用IDE提示",
          "slug": "使用ide提示"
        },
        {
          "level": 2,
          "title": "配置别名(宏)",
          "slug": "配置别名-宏"
        },
        {
          "level": 3,
          "title": "配置与使用",
          "slug": "配置与使用"
        },
        {
          "level": 3,
          "title": "别名在引擎中的应用",
          "slug": "别名在引擎中的应用"
        },
        {
          "level": 3,
          "title": "使用英文命令和英文参数",
          "slug": "使用英文命令和英文参数"
        },
        {
          "level": 2,
          "title": "引号的使用场景",
          "slug": "引号的使用场景"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/info/",
      "relativePath": "info/README.md",
      "key": "v-9b8f5588",
      "path": "/info/"
    },
    {
      "frontmatter": {},
      "regularPath": "/info/fix.html",
      "relativePath": "info/fix.md",
      "key": "v-8e2ca3da",
      "path": "/info/fix.html"
    },
    {
      "title": "可视化UI制作器",
      "frontmatter": {},
      "regularPath": "/info/todo.html",
      "relativePath": "info/todo.md",
      "key": "v-24df6e6f",
      "path": "/info/todo.html",
      "headers": [
        {
          "level": 2,
          "title": "可视化UI制作器",
          "slug": "可视化ui制作器"
        }
      ]
    }
  ],
  "themeConfig": {
    "search": true,
    "nextLinks": true,
    "prevLinks": true,
    "sidebar": {
      "/guide/": [
        {
          "title": "前言 · 关于引擎",
          "path": "/guide/preface"
        },
        {
          "title": "基础 · 编写剧本",
          "path": "/guide/script"
        },
        {
          "title": "基础 · 基本配置",
          "path": "/guide/config"
        },
        {
          "title": "进阶 · 优化访问",
          "path": "/guide/assetzip"
        },
        {
          "title": "常见问题",
          "path": "/guide/problem"
        }
      ],
      "/extend/": [
        {
          "title": "编写命令",
          "path": "/extend/command"
        },
        {
          "title": "编写UI",
          "path": "/extend/ui"
        }
      ],
      "/info/": [
        {
          "title": "开发日志",
          "path": "/info/fix"
        },
        {
          "title": "更新计划",
          "path": "/info/todo"
        }
      ]
    },
    "sidebarDepth": 2,
    "displayAllHeaders": true,
    "locales": {
      "/": {
        "nav": [
          {
            "text": "首页",
            "link": "/"
          },
          {
            "text": "制作游戏",
            "link": "/guide/"
          },
          {
            "text": "编写扩展",
            "link": "/extend/"
          },
          {
            "text": "开发日志",
            "link": "/info/"
          },
          {
            "text": "Github",
            "link": "https://github.com/ahzvenol/StarNight-Engine"
          }
        ],
        "lastUpdated": "上次更新"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "StarNight Engine",
      "description": "",
      "path": "/"
    }
  }
}